Academy.Web/Areas/Account/Controllers/HomeController.cs
using Academy.Application.Services.Interfaces;
using Academy.Domain.ViewModels.Account;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Academy.Web.Areas.Account.Controllers
{
    public class HomeController : AccountBaseController
    {
        #region constructor
        private readonly IUserService _userService;
        public HomeController(IUserService userService)
        {
            _userService = userService;
        }
        #endregion

        #region Index
        public async Task<IActionResult> Index()
        {
            return View(await _userService.GetUserInformationByUserName(User.Identity.Name));
        }
        #endregion

        #region Change User Password 

        [HttpGet("Account/ChangePassword")]
        public IActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost("Account/ChangePassword"),ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassword(ChangeUserPasswordViewModel changePass)
        {
            if (!ModelState.IsValid)
                return View(changePass);

            var CurrentUserName = User.Identity.Name;

            var res = await _userService.ChangeUserPassword(CurrentUserName, changePass);

            switch (res)
            {
                case ChangeUserPasswordResult.OldPasswordIsWrong:
                    ModelState.AddModelError("OldPassword", "کلمه عبور فعلی اشتباه وارد شده است");
                    break;
                case ChangeUserPasswordResult.Success:
                    ViewBag.IsSuccess = true;
                    return View();

            }
            return View(changePass);
        }
        #endregion
    }
}

Academy.Web/Areas/Admin/Controllers/HomeController.cs
using Academy.Application.Security;
using Academy.Application.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Academy.Web.Areas.Admin.Controllers
{
    public class HomeController : AdminBaseController
    {
        #region constructor
        private readonly IUserService _userService;
        private readonly ISubscribeService _subscribeService;

        public HomeController(IUserService userService,ISubscribeService subscribeService)
        {
            _userService = userService;
            _subscribeService = subscribeService;
        }
        #endregion

        #region Index

        [PermissionChecker(1)]
        [HttpGet("Admin/Home/Index")]
        [HttpGet("Admin")]
        public async Task<IActionResult> IndexAsync()
        {
            ViewData["UserCount"] = await _userService.CountUsers();
            ViewData["SubscribeCount"] = await _subscribeService.SubscribeCount();
            var newUsers = await _userService.GetNewUsersForAdmin();
            return View(newUsers);
        }
        #endregion
    }
}

Academy.Web/Controllers/HomeController.cs
using Academy.Application.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using RestSharp;
using System;
using System.Threading.Tasks;

namespace Academy.Web.Controllers
{
    public class HomeController : SiteBaseController
    {
        #region constructor
        private readonly IUserService _userService;
        private readonly ICourseService _courseService;
        public HomeController(IUserService userService,ICourseService courseService)
        {
            _courseService = courseService;
            _userService = userService;
        }
        #endregion
     
        #region Index
        public async Task<IActionResult> Index()
        {
            return View(await _courseService.GetCourses());
        }
        #endregion

        #region Online Payment

        string merchant = "****-****-****-****";

        [HttpGet("OnlinePayment/{id}")]
        public async Task<IActionResult> OnlinePayment(long id)
        {
            try
            {

                if (HttpContext.Request.Query["Authority"] != "")
                {
                    string authority = HttpContext.Request.Query["Authority"];
                }
                var wallet = await _userService.GetWalletByWalletId(id);

                string authorityverify = HttpContext.Request.Query["Authority"];

                string url = "https://api.zarinpal.com/pg/v4/payment/verify.json?merchant_id=" +
                    merchant + "&amount="
                    + wallet.Amount + "&authority="
                    + authorityverify;

                var client = new RestClient(url);
                client.Timeout = -1;

                var request = new RestRequest(Method.POST);

                request.AddHeader("accept", "application/json");

                request.AddHeader("content-type", "application/json");

                IRestResponse response = client.Execute(request);

                Newtonsoft.Json.Linq.JObject jodata = Newtonsoft.Json.Linq.JObject.Parse(response.Content);
                string data = jodata["data"].ToString();

                Newtonsoft.Json.Linq.JObject jo = Newtonsoft.Json.Linq.JObject.Parse(response.Content);
                string errors = jo["errors"].ToString();

                if (data != "[]")
                {
                    string refid = jodata["data"]["ref_id"].ToString();
                    ViewBag.code = refid;
                    ViewBag.IsSuccess = true;
                    wallet.IsPay = true;
                    await _userService.UpdateWallet(wallet);
                    return View();
                }
                else if (errors != "[]")
                {

                    string errorscode = jo["errors"]["code"].ToString();
                    ViewBag.IsSuccess = false;
                    return View();

                }


            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }


            return View();
        }
        #endregion

        #region Status Code
        [HttpGet("404")]
        public IActionResult NotFoundPage()
        {
            return View();
        }
        #endregion

        #region aboutUs

        [HttpGet("About-us")]
        public IActionResult AboutUs()
        {
            return View();
        }
        #endregion
    }
}

Academy.Web/ViewComponents/AccountHeaderViewComponent.cs
using Academy.Application.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Academy.Web.ViewComponents
{
    public class AccountHeaderViewComponent:ViewComponent
    {
        #region constructor
        private readonly IUserService _userService;
        public AccountHeaderViewComponent(IUserService userService)
        {
            _userService = userService;
        }

        #endregion
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("AccountHeader",await _userService.GetUserInformationByUserName(User.Identity.Name));
        }
    
    }

}

Academy.Web/Areas/Account/Views/Home/ChangePassword.cshtml
@model Academy.Domain.ViewModels.Account.ChangeUserPasswordViewModel
@{
    ViewData["Title"] = "تغییر کلمه عبور";
}

@await Component.InvokeAsync("AccountHeader")

<section class="section mt-60">
    <div class="container mt-lg-3">
        <div class="row">
            <partial name="_AccountDashbord" />
            @if (ViewBag.IsSuccess == true)
            {
                <div class="alert alert-success" role="alert">رمز عبور شما با موفقیت تغییر کرد!</div>
            }
            <div class="col-lg-6 col-md-6">
                <div class="card border-0 rounded shadow">
                    <div class="card-body">
                        <h5 class="text-md-start text-center">@ViewData["Title"] :</h5>
                        <div class="row">
                            <div class="col-md-12 mt-4 pt-2">
                                <form asp-area="Account" asp-controller="Home" asp-action="ChangePassword" method="post">
                                    <div class="row mt-4">
                                        <div class="col-lg-12">
                                            <div class="mb-3">
                                                <label class="form-label">رمز عبور قدیمی : </label>
                                                <div class="form-icon position-relative">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-key fea icon-sm icons"><path d="M21 2l-2 2m-7.61 7.61a5.5 5.5 0 1 1-7.778 7.778 5.5 5.5 0 0 1 7.777-7.777zm0 0L15.5 7.5m0 0l3 3L22 7l-3-3m-3.5 3.5L19 4"></path></svg>
                                                    <input asp-for="OldPassword" class="form-control ps-5" placeholder="رمز قدیمی" required="">
                                                </div>
                                                <span asp-validation-for="OldPassword" class="text-danger"></span>
                                            </div>
                                        </div>

                                        <div class="col-lg-12">
                                            <div class="mb-3">
                                                <label class="form-label">رمز عبور جدید : </label>
                                                <div class="form-icon position-relative">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-key fea icon-sm icons"><path d="M21 2l-2 2m-7.61 7.61a5.5 5.5 0 1 1-7.778 7.778 5.5 5.5 0 0 1 7.777-7.777zm0 0L15.5 7.5m0 0l3 3L22 7l-3-3m-3.5 3.5L19 4"></path></svg>
                                                    <input asp-for="Password" class="form-control ps-5" placeholder="رمز جدید" required="">
                                                </div>
                                                <span asp-validation-for="Password" class="text-danger"></span>
                                            </div>
                                        </div>

                                        <div class="col-lg-12">
                                            <div class="mb-3">
                                                <label class="form-label">تایید رمز عبور جدید : </label>
                                                <div class="form-icon position-relative">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-key fea icon-sm icons"><path d="M21 2l-2 2m-7.61 7.61a5.5 5.5 0 1 1-7.778 7.778 5.5 5.5 0 0 1 7.777-7.777zm0 0L15.5 7.5m0 0l3 3L22 7l-3-3m-3.5 3.5L19 4"></path></svg>
                                                    <input asp-for="ConfirmPassword" class="form-control ps-5" placeholder="رمز عبور جدید" required="">
                                                </div>
                                                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                                            </div>
                                        </div>

                                        <div class="col-lg-12 mt-2 mb-0">
                                            <button type="submit" class="btn btn-primary">ذخیره رمز عبور </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

Academy.Web/Areas/Account/Views/Home/Index.cshtml
@model Academy.Domain.ViewModels.Account.InformationUserPanelViewModel
@using Academy.Application.Utils.Convertors
@{
    ViewData["Title"] = "پنل کاربری";
}

@await Component.InvokeAsync("AccountHeader")
<section class="section mt-60">
    <div class="container mt-lg-3">
        <div class="row">

            <div class="col-lg-12 col-md-12">

                <div class="border-bottom pb-4">
                    <div class="row">

                        <partial name="_AccountDashbord" />

                        <div class="col-md-6 mt-4">
                            <h5>جزئیات شخصی :</h5>
                            <div class="mt-4">
                                <div class="d-flex align-items-center">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-mail fea icon-ex-md text-muted me-3"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>
                                    <div class="flex-1">
                                        <h6 class="text-primary mb-0">ایمیل :</h6>
                                        <a class="text-muted">@Model.Email</a>
                                    </div>
                                </div>



                                <div class="d-flex align-items-center mt-3">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar fea icon-ex-md text-muted me-3"><polyline points="20 12 20 22 4 22 4 12"></polyline><rect x="2" y="7" width="20" height="5"></rect><line x1="12" y1="22" x2="12" y2="7"></line><path d="M12 7H7.5a2.5 2.5 0 0 1 0-5C11 2 12 7 12 7z"></path><path d="M12 7h4.5a2.5 2.5 0 0 0 0-5C13 2 12 7 12 7z"></path></svg>
                                    <div class="flex-1">
                                        <h6 class="text-primary mb-0">تاریخ ثبت نام :</h6><i class="feather-calendar"></i>
                                        <p class="text-muted mb-0">@Model.RegisterDate.ToShamsi()</p>
                                    </div>
                                </div>

                                <div class="d-flex align-items-center mt-3">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-phone fea icon-ex-md text-muted me-3"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg>
                                    <div class="flex-1">
                                        <h6 class="text-primary mb-0">شماره تلفن :</h6>
                                        <a class="text-muted">@Model.PhoneNumber</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>