Academy.Web/Areas/Admin/Controllers/RolesController.cs
using Academy.Application.Security;
using Academy.Application.Services.Interfaces;
using Academy.Domain.Entities.Account;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Academy.Web.Areas.Admin.Controllers
{

    public class RolesController : AdminBaseController
    {
        #region constructor
        private readonly IPermissionService _permissionService;
        public RolesController(IPermissionService permissionService)
        {
            _permissionService = permissionService;
        }
        #endregion

        #region Index
        [PermissionChecker(4)]
        [HttpGet("Admin/Roles")]
        public async Task<IActionResult> Index()
        {
            var Roles = await _permissionService.GetRoles();

            return View(Roles);
        }
        #endregion

        #region Create Role
        [PermissionChecker(4)]

        [HttpGet("Admin/Roles/Create")]
        public async Task<IActionResult> Create()
        {
            ViewData["Permissions"] = await _permissionService.GetAllPermission();
            return View();
        }
        [HttpPost("Admin/Roles/Create")]
        public async Task<IActionResult> Create(Role role, List<long> SelectedPermission)
        {
            if (!ModelState.IsValid)
            {
                return View(role);
            }

            //Add Role
            long roleId = await _permissionService.AddRole(role);

            //Add Permissions Role
            await _permissionService.AddPermissionToRole(roleId, SelectedPermission);

            return RedirectToAction("Index");
        }
        #endregion

        #region Edit Role
        [PermissionChecker(4)]

        [HttpGet("Admin/Roles/Edit/{Id}")]
        public async Task<IActionResult> Edit(long Id)
        {
            ViewData["Permissions"] = await _permissionService.GetAllPermission();
            ViewData["SelectedPermission"] = await _permissionService.GetPermissionsRole(Id);
            var role = await _permissionService.GetRoleByIdAsync(Id);

            if (role == null)
                return NotFound();

            return View(role);
        }
        [HttpPost("Admin/Roles/Edit/{Id}")]
        public async Task<IActionResult> Edit(Role EditRole, List<long> SelectedPermission)
        {
            ViewData["Permissions"] = await _permissionService.GetAllPermission();
            ViewData["SelectedPermission"] = await _permissionService.GetPermissionsRole(EditRole.Id);
            if (!ModelState.IsValid)
                return View(EditRole);

            //Update Role
            await _permissionService.UpdateRole(EditRole);

            //Update Permissions Role
            await _permissionService.UpdatePermissionRole(EditRole.Id, SelectedPermission);

            await _permissionService.SaveChanges();

            return RedirectToAction("Index");
        }
        #endregion

        #region Delete Role
        [PermissionChecker(4)]

        [HttpGet("Admin/Roles/Delete/{Id}")]
        public async Task<IActionResult> Delete(long Id)
        {
            ViewData["Permissions"] = await _permissionService.GetAllPermission();
            ViewData["SelectedPermission"] = await _permissionService.GetPermissionsRole(Id);

            var role = await _permissionService.GetRoleByIdAsync(Id);
            if (role == null)
                return NotFound();

            return View(role);
        }

        [HttpPost("Admin/Roles/Delete/{Id}")]
        public async Task<IActionResult> DeleteConfirmed(long Id)
        {
            ViewData["Permissions"] = await _permissionService.GetAllPermission();
            ViewData["SelectedPermission"] = await _permissionService.GetPermissionsRole(Id);

            await _permissionService.DeleteRole(Id);

            return RedirectToAction("Index");
        }
        #endregion

    }
}

Academy.Web/Areas/Admin/Controllers/UsersController.cs
using Academy.Application.Security;
using Academy.Application.Services.Interfaces;
using Academy.Domain.ViewModels.Account;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Academy.Web.Areas.Admin.Controllers
{
    public class UsersController : AdminBaseController
    {
        #region constructor
        private readonly IUserService _userService;
        private readonly IPermissionService _permissionService;
        public UsersController(IUserService userService, IPermissionService permissionService)
        {
            _userService = userService;
            _permissionService = permissionService;
        }
        #endregion

        #region filter users
        [PermissionChecker(2)]
        [HttpGet("/Admin/Users")]
        public async Task<IActionResult> Index(FilterUserViewModel filter)
        {
            return View(await _userService.FilterUsers(filter));
        }
        #endregion

        #region filter Deleted User
        [PermissionChecker(2)]
        [HttpGet("/Admin/DeletedUsers")]
        public async Task<IActionResult> DeletedUsers(FilterUserViewModel filter)
        {
            return View(await _userService.FilterDeletedUsers(filter));
        }
        #endregion

        #region Add User
        [PermissionChecker(6)]
        [HttpGet("/Admin/Users/Create")]
        public async Task<IActionResult> Create()
        {
            ViewData["Roles"] = await _permissionService.GetRoles();
            return View();
        }
        [PermissionChecker(6)]
        [HttpPost("/Admin/Users/Create"), ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateUserViewModel user)
        {
            ViewData["Roles"] = await _permissionService.GetRoles();
            if (!ModelState.IsValid)
            {
                return View(user);
            }
            var res = await _userService.CreateUserFromAdmin(user);
            switch (res)
            {
                case CreateUserResult.Success:
                    return RedirectToAction("Index");
                case CreateUserResult.UserExist:
                    ModelState.AddModelError("Email", "اطلاعات وارد شده قبلا در سیستم ثبت شده است");
                    break;
                case CreateUserResult.Error:
                    ModelState.AddModelError("Email", "ثبت کاربر جدید با خطا مواجه شد لطفا دوباره امتحان کنید!");
                    break;
            }
            return View(user);

        }
        #endregion

        #region Edit User
        [PermissionChecker(7)]

        [HttpGet("Admin/Users/Edit/{Id}")]
        public async Task<IActionResult> Edit(long Id)
        {
            var user = await _userService.GetUserByUserIdForShow(Id);

            ViewData["Roles"] = await _permissionService.GetRoles();

            return View(user);
        }

        [PermissionChecker(7)]
        [HttpPost("Admin/Users/Edit/{Id}"),ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditUserViewModel editUser)
        {
            ViewData["Roles"] = await _permissionService.GetRoles();
            if (!ModelState.IsValid)
            {
                return View(editUser);
            }
            var res = await _userService.EditUserFromAdmin(editUser);
            switch (res)
            {
                case EditUserResult.Success:
                   return RedirectToAction("Index");                   
                case EditUserResult.Error:
                    return NotFound();
            }
            return View(editUser);
        }
        #endregion

        #region Delete User
        [PermissionChecker(8)]
        [HttpGet("/Admin/Users/Delete/{Id}")]
        public async Task<IActionResult> Delete(long Id)
        {
            var user = await _userService.GetUserInformationById(Id);
            if (user == null)
                return NotFound();
            ViewData["UserId"] = Id;
            return View(user);
        }
        [PermissionChecker(8)]
        [HttpPost("/Admin/Users/Delete/{Id}")]
        public async Task<IActionResult> DeleteConfirmed(long Id)
        {
            await _userService.DeleteUserFromAdmin(Id);

            return RedirectToAction("Index");
        }
        #endregion

    }
}

Academy.Web/Controllers/SubscribeController.cs
using Academy.Application.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Academy.Web.Controllers
{

    public class SubscribeController : Controller
    {
        #region constructor
        private readonly IOrderService _orderService;
        private readonly IUserService _userService;
        public SubscribeController(IOrderService orderService, IUserService userService)
        {
            _orderService = orderService;
            _userService = userService;
        }

        #endregion

        #region Orders
        [Authorize]
        [HttpGet("AddSubscribeToOrder/{Id}")]
        public async Task<IActionResult> BuySubscribe(long Id)
        {
            var userId = await _userService.GetUserIdByUserName(User.Identity.Name);
            long subId = await _orderService.AddSubscribeToOrder(userId, Id);
            return Redirect("/Account/MyOrders/ShowOrders/" + subId);
        }
        #endregion
    }
}

Academy.Web/Views/Shared/Components/AdminSideBar/AdminSideBar.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">

    <a href="adLayout/index3.html" class="brand-link">
        <img src="~/images/Default/logo.jpg" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">پنل مدیریت</span>
    </a>


    <div class="sidebar">
        <div>

            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="info">
                    <a href="/Account" class="d-block">
                        @User.Identity.Name
                        <i class="nav-icon fa  fa-user text-secondary"></i>
                    </a>
                </div>
            </div>


            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                    <li class="nav-item has-treeview">
                        <a class="nav-link"  asp-area="Admin" asp-controller="Home" asp-action="Index">
                            <i class="nav-icon fa  fa-home"></i>
                            <p>
                               خانه
                                
                            </p>
                        </a>
                   
                    </li>


                    <li class="nav-item has-treeview">
                        <a class="nav-link">
                            <i class="nav-icon fa  fa-user"></i>
                            <p>
                                مدیریت کاربران
                                <i class="right fa fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a asp-area="Admin" asp-controller="Users" asp-action="Index" class="nav-link">
                                    <i class="fa fa-users nav-icon"></i>
                                    <p>لیست کاربران</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-area="Admin" asp-controller="Users" asp-action="DeletedUsers" class="nav-link">
                                    <i class="fa fa-users nav-icon text-danger"></i>
                                    <p>لیست کاربران حذف شده</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-area="Admin" asp-controller="Users" asp-action="Create" class="nav-link">
                                    <i class="fa fa-user-plus nav-icon"></i>
                                    <p>افزودن کاربر جدید</p>
                                </a>
                            </li>

                        </ul>
                    </li>

                    <li class="nav-item has-treeview">
                        <a class="nav-link">
                            <i class="nav-icon fa  fa-user-secret"></i>
                            <p>
                                مدیریت نقش ها
                                <i class="right fa fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a asp-area="Admin" asp-controller="Roles" asp-action="Index" class="nav-link">
                                    <i class="fa fa-key nav-icon"></i>
                                    <p>لیست نقش ها</p>
                                </a>
                            </li>


                        </ul>
                    </li>

                    <li class="nav-item has-treeview">
                        <a class="nav-link">
                            <i class="nav-icon fa  fa-newspaper-o"></i>
                            <p>
                                مدیریت مقالات
                                <i class="right fa fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a asp-area="Admin" asp-controller="Article" asp-action="Index" class="nav-link">
                                    <i class="fa fa-newspaper-o"></i>
                                    <p>لیست مقالات</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-area="Admin" asp-controller="Article" asp-action="DeletedArticle" class="nav-link">
                                    <i class="fa fa-newspaper-o text-danger"></i>
                                    <p>لیست مقالات حذف شده</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-area="Admin" asp-controller="Article" asp-action="Create" class="nav-link">
                                    <i class="fa fa-pencil-square-o"></i>
                                    <p>افزودن مقاله</p>
                                </a>
                            </li>



                        </ul>
                    </li>

                    <li class="nav-item has-treeview">
                        <a class="nav-link">
                            <i class="nav-icon fa  fa-play-circle"></i>
                            <p>
                                مدیریت دوره ها
                                <i class="right fa fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a asp-area="Admin" asp-controller="Courses" asp-action="Index" class="nav-link">
                                    <i class="fa fa-play"></i>
                                    <p>لیست دوره های سایت</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-area="Admin" asp-controller="Courses" asp-action="Create" class="nav-link">
                                    <i class="fa fa-plus"></i>
                                    <p>افزودن دوره</p>
                                </a>
                            </li>



                        </ul>
                    </li>

                    <li class="nav-item has-treeview">
                        <a class="nav-link">
                            <i class="nav-icon fa  fa-btc"></i>
                            <p>
                                مدیریت اشتراک ها
                                <i class="right fa fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a asp-area="Admin" asp-controller="Subscribe" asp-action="Index" class="nav-link">
                                    <i class="fa fa-list"></i>
                                    <p>لیست اشتراک ها</p>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class="nav-item has-treeview">
                        <a class="nav-link">
                            <i class="nav-icon fa  fa-tag"></i>
                            <p>
                                کد تخفیف
                                <i class="right fa fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a asp-area="Admin" asp-controller="Discount" asp-action="Index" class="nav-link">
                                    <i class="fa fa-star"></i>
                                    <p>لیست کد ها</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-area="Admin" asp-controller="Discount" asp-action="Create" class="nav-link">
                                    <i class="fa fa-plus"></i>
                                    <p>ایجاد کد </p>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </nav>

        </div>
    </div>

</aside>