Academy.Web/Areas/Admin/Controllers/ArticleController.cs
using Academy.Application.Security;
using Academy.Application.Services.Interfaces;
using Academy.Application.Utils;
using Academy.Application.Utils.Convertors;
using Academy.Domain.Entities.Article;
using Academy.Domain.ViewModels.Article;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Academy.Web.Areas.Admin.Controllers
{
    public class ArticleController : AdminBaseController
    {
        #region constructor
        private readonly IArticleService _articleService;
        private readonly IUserService _userService;
        public ArticleController(IArticleService articleService, IUserService userService)
        {
            _articleService = articleService;
            _userService = userService;
        }
        #endregion

        #region filter article
        [PermissionChecker(3)]
        [HttpGet("Admin/Article")]
        public async Task<IActionResult> Index(FilterArticleViewModel filterArticle)
        {
            return View(await _articleService.FilterArticleAsync(filterArticle));
        }
        [PermissionChecker(3)]
        [HttpGet("Admin/Article/DeletedArticle")]
        public async Task<IActionResult> DeletedArticle(FilterArticleViewModel filterArticle)
        {
            return View(await _articleService.FilterDeletedArticleAsync(filterArticle));
        }
        #endregion

        #region Create
        [PermissionChecker(9)]
        [HttpGet("Admin/Article/Create")]
        public async Task<IActionResult> Create()
        {
            ViewData["UserId"] = await _userService.GetUserIdByUserName(User.Identity.Name);

            return View();
        }


        [HttpPost("Admin/Article/Create"), ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateArticleViewModel createArticle)
        {
            if (!ModelState.IsValid)
                return View(createArticle);

            var res = await _articleService.CreateArticle(createArticle);
            switch (res)
            {
                case CreateArticleResult.Success:
                    return RedirectToAction("Index");
                case CreateArticleResult.Error:
                    ModelState.AddModelError("Title", "خطایی در انجام عملیات رخ داد!");
                    break;
            }

            return View(createArticle);

        }
        #endregion

        #region Edit
        [PermissionChecker(10)]
        [HttpGet("Admin/Article/Edit/{Id}")]
        public async Task<IActionResult> Edit(long Id)
        {
            var article = await _articleService.GetInformationArticleForEdit(Id);
            if (article == null)
                return NotFound(Id);

            return View(article);
        }

        [HttpPost("Admin/Article/Edit/{Id}"), ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditArticleViewModel editArticle)
        {
            if (!ModelState.IsValid)
                return View(editArticle);

            var res = await _articleService.EditArticle(editArticle);
            switch (res)
            {
                case EditArticleResult.Success:
                    return RedirectToAction("Index");
                case EditArticleResult.Error:
                    ModelState.AddModelError("Title", "خطایی در انجام عملیات رخ داد!");
                    break;
            }

            return View(editArticle);

        }
        #endregion

        #region Delete
        [PermissionChecker(11)]
        [HttpGet("Admin/Article/Delete/{Id}")]
        public async Task<IActionResult> Delete(long Id)
        {
            //TODO: take it to the service
            var article = await _articleService.GetArticleById(Id);
            if (article == null)
                return NotFound();
            var model = new DetailsArticleViewModel()
            {
                Id = article.Id,
                UserId = article.UserId,
                Description = article.Description,
                CreateDate = article.CreateDate,
                IsDelete = article.IsDelete,
                ShortDescription = article.ShortDescription,
                Slug = article.Slug,
                Title = article.Title,
                Visit = article.Visit,
                ImageName = article.ImageName
            };
            ViewData["UserName"] = await _userService.GetUserNameById(article.UserId);

            return View(model);

        }
        [HttpPost("Admin/Article/Delete/{Id}"),ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long Id)
        {
            await _articleService.DeleteArticle(Id);
            return RedirectToAction("Index");
        }
        #endregion

        #region Detail
        [PermissionChecker(3)]
        [HttpGet("Admin/Article/Detail/{Id}")]
        public async Task<IActionResult> Detail(long Id)
        {
            var article = await _articleService.GetDetailsArticle(Id);
            if (article == null)
                return NotFound();
            ViewData["UserName"] = await _userService.GetUserNameById(article.UserId);
            return View(article);
        }
        #endregion

  
    }
}

Academy.Web/Controllers/ArticlesController.cs
using Academy.Application.Services.Interfaces;
using Academy.Domain.ViewModels.Article;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Academy.Web.Controllers
{
    public class ArticlesController : SiteBaseController
    {
        #region constructor 
        private readonly IArticleService _articleService;
        private readonly IUserService _userService;
        public ArticlesController(IArticleService articleService,IUserService userService)
        {
            _articleService = articleService;
            _userService = userService;
        }
        #endregion

        #region Index
        [HttpGet("articles")]
        public async Task<IActionResult> Index(FilterListArticlesViewModel filter)
        {
            var articles = await _articleService.GetArticlesList(filter);
           
            return View(articles);
        }
        #endregion

        #region Detail Article

        [HttpGet("article/news-article/{slug}")]
        public async Task<IActionResult> NewsArticle(string slug)
        {
            var article = await _articleService.GetArticleBySlug(slug);
            if (article == null)
                return NotFound();
            ViewData["Author"] = await _userService.GetUserNameById(article.UserId);
            ViewData["SiteUrl"]= $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}";
            return View(article);
        }
        #endregion
    }
}

Academy.Web/ViewComponents/SiteFooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Academy.Web.ViewComponents
{
    public class SiteFooterViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("SiteFooter");
        }
    }
}

Academy.Web/ViewComponents/SiteHeaderViewComponent.cs
using Academy.Application.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Academy.Web.ViewComponents
{
    public class SiteHeaderViewComponent:ViewComponent
    {
     
  
        public  IViewComponentResult Invoke()
        {
            
            return View("SiteHeader");
        }
    }
}

Academy.Web/Views/Articles/Index.cshtml
@model Academy.Domain.ViewModels.Article.FilterListArticlesViewModel
@using Academy.Application.Utils.Convertors
@using Academy.Application.FilePath
@{
    ViewData["Title"] = "لیست مقالات";
}
@await Component.InvokeAsync("SiteHeader")


<section class="bg-half d-table w-100" style="background: url('/images/Default/articles-bg.jpg') center center;">
    <div class="bg-overlay"></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12 text-center">
                <div class="page-next-level">
                    <h3 class="title text-white title-dark">@ViewData["Title"]</h3>
                    <div class="page-next">
                        <nav aria-label="breadcrumb" class="d-inline-block">
                            <ul class="breadcrumb bg-white rounded shadow mb-0">
                                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">کوین گلس </a></li>
                                <li class="breadcrumb-item"><a asp-controller="articles" asp-action="Index">مقالات </a></li>
                                <li class="breadcrumb-item active" aria-current="page">لیست مقالات</li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="position-relative">
    <div class="shape overflow-hidden text-white">
        <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
        </svg>
    </div>
</div>
<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 mb-4 pb-2">
                <div class="component-wrapper rounded shadow">
                    <div class="p-4">
                        <div class="subcribe-form">
                            <form asp-controller="Articles" asp-action="Index" method="get">
                                <input type="hidden" asp-for="Page" />
                                <input asp-for="Search" class="form-control rounded-pill shadow" placeholder="عنوان مورد نظر..." aria-describedby="newssubscribebtn">
                                <button type="submit" class="btn btn-pills btn-primary">جستجو</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section">
    <div class="container">
        <div class="row">

            @if (Model.Entities.Any())
            {
                @foreach (var item in Model.Entities)
                {
                    <div class="col-lg-6 col-12 mb-4 pb-2">
                        <div class="card blog rounded border-0 shadow overflow-hidden">
                            <div class="row align-items-center g-0">
                                <div class="col-md-6">
                                    <img src="@(FilePaths.ArticlePath + item.ImageName)" class="img-fluid" alt="">
                                    <div class="overlay bg-dark"></div>
                                    <div class="author">
                                        <small class="text-light user d-block"><i class="uil uil-user"></i> کوین گلس</small>
                                        <small class="text-light date"><i class="uil uil-calendar-alt"></i>@item.CreateDate.ToShamsi()</small>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="card-body content">
                                        <h5><a class="card-title title text-dark">@item.Title</a></h5>
                                        <p class="text-muted mb-0">@item.ShortDescription</p>
                                        <div class="post-meta d-flex justify-content-between mt-3">
                                            <ul class="list-unstyled mb-0">
                                            </ul>
                                            <a asp-controller="Articles" asp-action="NewsArticle" asp-route-slug="@item.Slug" class="text-muted readmore">ادامه مطلب  <i class="uil uil-angle-left-b align-middle"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }

                <div class="col-12">
                    <ul class="pagination justify-content-center mb-0">
                        @if (Model.Page > 1)
                        {
                            <li class="page-item"><a class="page-link" onclick="changePage(@(Model.Page-1))" aria-label="Previous">قبلی </a></li>
                        }
                        else
                        {
                            <li class="page-item disabled"><a class="page-link " aria-label="Previous">قبلی </a></li>

                        }
                        @for (int i = Model.StartPage; i < Model.EndPage; i++)
                        {
                            <li class="@(i==Model.Page?"page-item active":"page-item")" onclick="changePage(@(i))"><a class="page-link">@i</a></li>
                        }
                        @if (Model.Page < Model.EndPage)
                        {

                            <li onclick="changePage(@(Model.Page +1))" class="page-item"><a class="page-link" aria-label="Next">بعدی </a></li>
                        }
                        else
                        {
                            <li class="page-item disabled"><a class="page-link" aria-label="Next">بعدی </a></li>

                        }




                    </ul>
                </div>
            }
            else
            {
                <div class="row">
                    <h5 class="title mb-4 text-center text-dark">موردی برای نمایش یافت نشد!</h5>
                </div>
            }




        </div>
    </div>
</section>
@await Component.InvokeAsync("SiteFooter")
@section Scripts {
    <script src="/lib/Js/customjs.js"></script>
}

Academy.Web/Views/Articles/NewsArticle.cshtml
@model Academy.Domain.ViewModels.Article.ShowArticleViewModel
@using Academy.Application.Utils.Convertors;
@using Academy.Application.FilePath;

@{
    ViewData["Title"] = Model.Title;
    var siteUrl = ViewData["SiteUrl"];
    var postUrl = $"{siteUrl}/post/{Model.Slug}";
}

@await Component.InvokeAsync("SiteHeader")
<section class="bg-half d-table w-100" style="background: url('/images/Default/articles-bg.jpg') center center;">
    <div class="bg-overlay"></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12 text-center">
                <div class="page-next-level">
                    <h3 class="title text-white title-dark"><a class="text-center text-light" asp-area="" asp-controller="Home" asp-action="Index">آکادمی کوین گلس</a></h3>
                    <div class="page-next">
                        <nav aria-label="breadcrumb" class="d-inline-block">
                            <ul class="breadcrumb bg-white rounded shadow mb-0">
                                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">کوین گلس </a></li>
                                <li class="breadcrumb-item"><a asp-controller="articles" asp-action="Index">مقالات </a></li>
                                <li class="breadcrumb-item active" aria-current="page">@Model.Title</li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="position-relative">
    <div class="shape overflow-hidden text-white">
        <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
        </svg>
    </div>
</div>


<section class="section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-10">
                <div class="row">
                    <div class="col-md-2 d-none d-md-block">
                        <ul class="list-unstyled text-center sticky-bar social-icon mb-0">
                            <li class="mb-3 h6">اشتراک </li>
                            <li><a href="https://www.facebook.com/sharer/sharer.php?u=@postUrl" class="rounded"><i data-feather="facebook" class="fea icon-sm fea-social"></i></a></li>
                            <li><a href="https://twitter.com/intent/tweet?url=@postUrl" class="rounded"><i data-feather="twitter" class="fea icon-sm fea-social"></i></a></li>
                       
                        </ul>
                    </div>
                    <div class="col-md-10">
                        <p class="text-muted">@Model.ShortDescription</p>
                        <ul class="list-unstyled d-flex justify-content-between mt-4">
                            <li class="list-inline-item user me-2"><a href="javascript:void(0)" class="text-muted"><i class="uil uil-user text-dark"></i> @ViewData["Author"]</a></li>
                            <li class="list-inline-item date text-muted"><i class="uil uil-calendar-alt text-dark"></i>@Model.CreateDate.ToShamsi()</li>
                        </ul>
                        <img src="@(FilePaths.ArticlePath + Model.ImageName)" class="img-fluid rounded-md shadow">            
                        @Html.Raw(Model.Description)
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@await Component.InvokeAsync("SiteFooter")